package com.moviebooking.model;

/**
 * Movie is a POJO (Plain Old Java Object) class.
 * It represents one row of the "Movie" table in our database.
 * Each field here matches exactly one column in the Movie table.
 */
public class Movie {

    // These fields match the columns in the Movie table
    private int movieId;
    private String movieName;
    private String genre;
    private String language;
    private int durationMinutes;
    private String description;
    private String imageUrl;

    // ---------- Constructors ----------

    // No-argument constructor
    public Movie() {
    }

    // Parameterized constructor WITHOUT movieId
    // Used when INSERTING a new movie (movieId is auto-generated by MySQL)
    public Movie(String movieName, String genre, String language, int durationMinutes,
                 String description, String imageUrl) {
        this.movieName = movieName;
        this.genre = genre;
        this.language = language;
        this.durationMinutes = durationMinutes;
        this.description = description;
        this.imageUrl = imageUrl;
    }

    // Parameterized constructor WITH movieId
    // Used when READING a movie from the database (movieId already exists)
    public Movie(int movieId, String movieName, String genre, String language, int durationMinutes,
                 String description, String imageUrl) {
        this.movieId = movieId;
        this.movieName = movieName;
        this.genre = genre;
        this.language = language;
        this.durationMinutes = durationMinutes;
        this.description = description;
        this.imageUrl = imageUrl;
    }

    // ---------- Getters and Setters ----------

    public int getMovieId() {
        return movieId;
    }

    public void setMovieId(int movieId) {
        this.movieId = movieId;
    }

    public String getMovieName() {
        return movieName;
    }

    public void setMovieName(String movieName) {
        this.movieName = movieName;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public int getDurationMinutes() {
        return durationMinutes;
    }

    public void setDurationMinutes(int durationMinutes) {
        this.durationMinutes = durationMinutes;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    // ---------- toString() ----------
    @Override
    public String toString() {
        return "Movie [movieId=" + movieId + ", movieName=" + movieName + ", genre=" + genre +
                ", language=" + language + ", durationMinutes=" + durationMinutes +
                ", imageUrl=" + imageUrl + "]";
    }
}