package com.moviebooking.model;

/**
 * Theatre is a POJO (Plain Old Java Object) class.
 * It represents one row of the "Theatre" table in our database.
 * Each field here matches exactly one column in the Theatre table.
 */
public class Theatre {

    // These fields match the columns in the Theatre table
    private int theatreId;
    private String theatreName;
    private String location;

    // ---------- Constructors ----------

    // No-argument constructor
    public Theatre() {
    }

    // Parameterized constructor WITHOUT theatreId
    // Used when INSERTING a new theatre (theatreId is auto-generated by MySQL)
    public Theatre(String theatreName, String location) {
        this.theatreName = theatreName;
        this.location = location;
    }

    // Parameterized constructor WITH theatreId
    // Used when READING a theatre from the database (theatreId already exists)
    public Theatre(int theatreId, String theatreName, String location) {
        this.theatreId = theatreId;
        this.theatreName = theatreName;
        this.location = location;
    }

    // ---------- Getters and Setters ----------

    public int getTheatreId() {
        return theatreId;
    }

    public void setTheatreId(int theatreId) {
        this.theatreId = theatreId;
    }

    public String getTheatreName() {
        return theatreName;
    }

    public void setTheatreName(String theatreName) {
        this.theatreName = theatreName;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    // ---------- toString() ----------
    @Override
    public String toString() {
        return "Theatre [theatreId=" + theatreId + ", theatreName=" + theatreName +
                ", location=" + location + "]";
    }
}