package com.moviebooking.model;

/**
 * User is a POJO (Plain Old Java Object) class.
 * It represents one row of the "User" table in our database.
 * Each field here matches exactly one column in the User table.
 */
public class User {

    // These fields match the columns in the User table
    private int userId;
    private String fullName;
    private String email;
    private String password;
    private String phone;
    private String role;

    // ---------- Constructors ----------

    // No-argument constructor (empty constructor)
    // Needed so we can create a User object and set values later using setters
    public User() {
    }

    // Parameterized constructor WITHOUT userId
    // Useful when we are INSERTING a new user (userId is auto-generated by MySQL, so we don't have it yet)
    public User(String fullName, String email, String password, String phone, String role) {
        this.fullName = fullName;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.role = role;
    }

    // Parameterized constructor WITH userId
    // Useful when we are READING a user from the database (userId already exists)
    public User(int userId, String fullName, String email, String password, String phone, String role) {
        this.userId = userId;
        this.fullName = fullName;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.role = role;
    }

    // ---------- Getters and Setters ----------
    // These allow other classes to safely read (get) and update (set) each field

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    // ---------- toString() ----------
    // Helpful for printing/debugging a User object directly (e.g., System.out.println(user))
    @Override
    public String toString() {
        return "User [userId=" + userId + ", fullName=" + fullName + ", email=" + email +
                ", phone=" + phone + ", role=" + role + "]";
    }
}